/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/container/index.vue')['default']
    Converse: typeof import('./src/components/converse/index.vue')['default']
    ConverseSourceAction: typeof import('./src/components/converse/SourceAction.vue')['default']
    ConverseVoice: typeof import('./src/components/converse/Voice.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutChatList: typeof import('./src/components/layout/chat-list.vue')['default']
    LayoutContent: typeof import('./src/components/layout/content.vue')['default']
    LoginPopup: typeof import('./src/components/login/popup.vue')['default']
    MessageCard: typeof import('./src/components/message/card.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    PublishPopup: typeof import('./src/components/publish/popup.vue')['default']
    RecordPopup: typeof import('./src/components/record/popup.vue')['default']
    RecordWave: typeof import('./src/components/record/Wave.vue')['default']
    SearchCard: typeof import('./src/components/search/card.vue')['default']
    SharePopup: typeof import('./src/components/share/popup.vue')['default']
    Tabs: typeof import('./src/components/tabs/index.vue')['default']
    TabsItem: typeof import('./src/components/tabs/item.vue')['default']
    WdActionSheet: typeof import('wot-design-uni/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCheckbox: typeof import('wot-design-uni/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdImg: typeof import('wot-design-uni/components/wd-img/wd-img.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdText: typeof import('wot-design-uni/components/wd-text/wd-text.vue')['default']
    WdTextarea: typeof import('wot-design-uni/components/wd-textarea/wd-textarea.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
