export enum API {
  AUTO_LOGIN = '/buyer/passport/connect/miniProgram/phone/once/auto-login',
  REFRESH_TOKEN = '/buyer/passport/member/refresh',
  SSE = '/buyer/chat/sse/ai-proxy/send-query-combined',
  USER_INFO = '/buyer/passport/member/getImUser',
  GET_MESSAGE_LIST = '/buyer/chatQuery/getByPage',
  GET_CHAT_LIST = '/buyer/chat/chat/getByPage',
  ADD_CHAT = '/buyer/chat/chat/add',
  ADD_COLLECT = '/buyer/chat/chatQueryCollect/add',
  UPDATE_CHAT = '/buyer/chat/chat/updateByChatId',
  DELETE_CHAT = '/buyer/chat/chat/deleteByChatId',
  ADD_PUBLISH_MESSAGE = '/buyer/content/publish/publishContentFromChatQuery',
  GET_PUBLISH_MESSAGE_LIST = '/buyer/content/publish/getByPageForIndex',
  SHARE_MESSAGE = '/buyer/chat/chatQueryShare/add',
  GET_SHARE_MESSAGE_LIST = '/buyer/chat/chatQueryShare/getListByShareId',
  GET_PUBLIC_MESSAGE_DETAIL = '/buyer/content/publish/getContentDetailForSelfAndOthers',
  FOLLOW_USER = '/buyer/member/my/follow',
  ADD_COMMENT = '/buyer/content/comment/addComment/withFiles',
}
